### ISSUE TITLE
The plugin doesn't work with DokuWiki Release 2020-07-29 "Hogfather"

### ISSUE THREAD

**Issue by xaozai** [splitbrain/dokuwiki-plugin-captcha#113]
PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function i    magecreatetruecolor() in /doku/lib/plugins/captcha/helper.php:365

**Comment by splitbrain** [comment]
Your PHP is missing libGD

**Comment by xaozai** [comment]
Thank you!
