### ISSUE TITLE
Audio text is different from image text

### ISSUE THREAD

**Issue by adakaleh** [splitbrain/dokuwiki-plugin-captcha#115]
In both _Image+Audio_ and _SVG+Audio_, the audio text is completely different from the image text. The audio text is considered incorrect. Only the text in the image works.

**Comment by demiankatz** [comment]
I am seeing this problem after upgrading to "Igor" in my test environment. When I revert to "Hogfather," the problem goes away. Has anyone made any progress investigating what is going on here?

**Comment by demiankatz** [comment]
Thanks, @splitbrain!

**Comment by adakaleh** [comment]
Quoting the commit:
> It seems browsers pass different accept-encoding headers now for the
> audio request, breaking auth_browseruid()

Ok, so it's my fault for [adding](https://github.com/splitbrain/dokuwiki/pull/3268) Accept-Encoding to `auth_browseruid()`. We should remove it, as it may have also broken other things. PR coming soon.

I thought browsers send the same Accept-Encoding header for all requests, but I was wrong. Here is why Firefox disables Accept-Encoding for embedded media:

- https://github.com/bolucat/Firefox/blob/32403d9142cf797ea2f02ed3330109a9395ac2c9/dom/html/HTMLMediaElement.cpp#L6619
- https://bugzilla.mozilla.org/show_bug.cgi?id=614760

The embedded media in this case is the `<audio>` element added [here](https://github.com/splitbrain/dokuwiki-plugin-captcha/blob/186227361d0efe9f0e20bd52c87dfbf939efb53a/script.js#L15-L30).
