### ISSUE TITLE
It seems taht the plugin doesn't work with higer php version.

### ISSUE THREAD

**Issue by FunctionSir** [splitbrain/dokuwiki-plugin-captcha#116]
I's my plugin version too old?
I got "Fatal error: Array and string offset access syntax with curly braces is no longer supported in /var/www/main/lib/plugins/captcha/helper.php on line 285"
when I use PHP8.0.8.

**Comment by FunctionSir** [comment]
It can run well on PHP7.4

**Comment by splitbrain** [comment]
fixed
