### ISSUE TITLE
PHP 8 - Warning: Undefined array key

### ISSUE THREAD

**Issue by temperatur** [splitbrain/dokuwiki-plugin-captcha#130]
Hi, 
i am getting the warning:

`Warning: Undefined array key "REMOTE_USER" in /{Path}/lib/plugins/captcha/action.php on line 190 `

on the login form with php 8.
I gues this is because  **$_SERVER['REMOTE_USER']** is not set for not logged in users.

**Comment by JoBongHyeon** [comment]
https://github.com/splitbrain/dokuwiki/issues/3753#issuecomment-1226776398

**Comment by splitbrain** [comment]
same as #131
