### ISSUE TITLE
Captcha not working anymore after last update

### ISSUE THREAD

**Issue by casperklein** [splitbrain/dokuwiki-plugin-captcha#137]
DW Release: `2023-04-04 "Jack Jackrum"`
Captcha Plugin Version:  `2022-08-27`

I recently updated to the latest dokuwiki/captcha-plugin version. After that I noticed, that the captcha plugin does not work anymore.

I am using it together with the bureaucracy-plugin. I am using a fixed phrase as captcha. It's possible to submit the form with the captcha field empty or putting anything wrong there.

PS: There is also already an issue open [here](https://github.com/splitbrain/dokuwiki-plugin-bureaucracy/issues/323).

**Comment by ParoTheParrot** [comment]
@casperklein : is this issue really solved ? Works the captcha plugin with Jack Jackrum in the expected way?
In case, please update the compatibility information on https://www.dokuwiki.org/plugin:captcha.
TIA, Paro
