### ISSUE TITLE
MOBILE DEVICE and CAPTA plugin

### ISSUE THREAD

**Issue by WPS12TA** [splitbrain/dokuwiki-plugin-captcha#140]
When accessing the CAPTCHA screen and registering, the alignment of the text boxes is centered which makes the box flow off to the right on some mobile devices in portrait mode (in non desktop mode) particularly if the text box is expanded.
I think the problem would be easily solved with LEFT alignment of the line showing the svg captcha text speaker icon and box. That would greatly increase usability. Could the box be tinted to invite input?
In the configuration section could the default values be made clear so they can be reverted to if changed with a poor outcome and a default value for just that field is desired?

**Comment by splitbrain** [comment]
Please provide additional info (used template, screenshots in different resolutions showing the problem).

**Comment by WPS12TA** [comment]
Thanks! I turned on SVG and always use then got thus screen, while trying to reproduce the screen which was with a phone and the standard template.
I'm wary of getting logged out, but luckily I had another instance to revert the settings to the prefilled in 
![Screenshot_20231220-143725_Chrome](https://github.com/splitbrain/dokuwiki-plugin-captcha/assets/142661852/19496747-b7dc-4705-9572-2ac7fa2e27aa)
Javascript version which HAS been working both silently and effectively. 
Paul

**Comment by splitbrain** [comment]
Huh? That screenshot seems to be about something completely different than your initial post.

I am closing this now. Please open separate tickets for separate issues. Be sure to include all relevant data. Eg. when you get an error message that tells you that there is more info in the logs, then post that info from the logs.

**Comment by WPS12TA** [comment]
Sorry, I just changed the Captcha options and I was just logging out and
wanting to log in again to reproduce the issue for you. Then I got a screen
that stopped me logging in, so fearing getting locked out I stopped there.
I was not trying to divert the issue. I m sure you are busy and I wanted to
reply to you ASAP.
Paul
