### ISSUE TITLE
Text prefilled with Javascript, DOESN'T MATCH

### ISSUE THREAD

**Issue by chang-zhao** [splitbrain/dokuwiki-plugin-captcha#35]
http://earth.zen-do.ru
"Text prefilled with Javascript" was set.

1. Some user reported that, using Firefox, he wasn't able to register, always getting an error:
"Sorry, but the CAPTCHA wasn't answered correctly. Maybe you're not human at all?"

2. I tried myself and could register.
(FF 27.0.1 with NoScript, scripts for that site Allowed).

But when I tried to comment with Discussion plugin, I also got a message:
"Sorry, but the CAPTCHA wasn't answered correctly. Maybe you're not human at all?"

3. When I tried to use IE 9 (x64), CAPTCHA with Discussion also didn't work, the same way.

**Comment by splitbrain** [comment]
Problems with other plugins should be reported to those plugin's tracker.
