### ISSUE TITLE
Doesn't work with Chrome

### ISSUE THREAD

**Issue by Petrouchka** [splitbrain/dokuwiki-plugin-captcha#42]
It works well with Chromium + Linux MINT or Mozilla Firefox + Linux MINT but it doesn't work with Chrome navigator version 37.0.2062.102 m + Windows XP Pro :

Warning: mdecrypt_generic(): An empty string was passed in /home/energino/public_html/urbolienne/wiki/inc/phpseclib/Crypt_Base.php on line 915
DÃ©solÃ©, vous n'avez pas rÃ©pondu correctement au test anti-spam. Peut-Ãªtre n'Ãªtes vous pas humain ?

**Comment by splitbrain** [comment]
works for me
