### ISSUE TITLE
CAPTCHA for dokuwiki login

### ISSUE THREAD

**Issue by crysman** [splitbrain/dokuwiki-plugin-captcha#48]
I've unsuccessfully tried to find how to use this CAPTCHA plugin (or another one) also for the dokuwiki login page :(

Any hints? Thank you

**Comment by crash5** [comment]
Try this: https://github.com/turnermm/captcha-login-for-Dokuwiki

**Comment by crysman** [comment]
I found something already (maybe it is even the same as you have posted :) thanks
