### ISSUE TITLE
Under Detritus: Does not block the protected operation on incorrect input

### ISSUE THREAD

**Issue by BorutAtGit** [splitbrain/dokuwiki-plugin-captcha#67]
After entering an incorrect captcha string, the red message saying that the input was wrong appears (as expected), but **the underlying operation that should be protected with captcha (such as a login) succeeds** (which is very wrong, making captcha de facto useless!).

This is 100% reproducible at my place and apparently independent of the browser used, or of the captcha mode.

Dokuwiki: 2015-08-10a "Detritus". Captcha newly reinstalled. PHP: 5.4.

**Comment by splitbrain** [comment]
Does this happen with login only or with all protected actions (like posting?)

**Comment by BorutAtGit** [comment]
Yes, it happens only with login. Captcha-protection works as expected when posting. (Sorry, I have not expected that difference and have not checked that earlier.) 

I have now tested it with both dokuwiki and monobook tamplates and there appears to be no difference: only login seems not to be protected by captcha.

**Comment by splitbrain** [comment]
just to make sure, what auth mechanism are you using? authplain?

**Comment by BorutAtGit** [comment]
Yes, "Plain Auth Plugin", http://www.dokuwiki.org/plugin:authplain

**Comment by splitbrain** [comment]
I can not reproduce this in a current wiki and with a current plugin. So I assume this has been fixed.
